### ISSUE TITLE
Bug: dnssrvnoa+ memcached client fails with invalid SRV records

### ISSUE THREAD

**Issue by snapydziuba** [grafana/mimir#12713]
### What is the bug?

We updated our mimir-distributed Helm Chart to 5.8.0 recently which include the changes from PR #11041, with this our memcached clients fail to connect with SRV records resolving to IPv6 addresses (AAAA records). The error message claims the SRV response is "invalid" but manual DNS lookups work fine, as the error message returns a AAAA instead of SRV record.

The generated Configmap configures memcached addresses like this:
` addresses: dnssrvnoa+mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.:11211`

### How to reproduce it?

To Reproduce

1. Deploy Mimir in an IPv6-only Kubernetes cluster
2. Enable memcached caches (chunks-cache, index-cache, etc.)
3. DNS records resolve but target AAAA instead of SRV
4. Loki logs show: `msg="failed to resolve addresses for memcached" addresses=dnssrvnoa+mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.:11211 err="lookup SRV records \"mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.\": invalid SRV response record mimir-distributed-metadata-cache-1.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.\t3\tIN\tAAAA\t2a05:d024:c0:3:6563::14"`

- Manual SRV lookup works: nslookup -type=SRV _memcached-client._tcp.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local

  ```nslookup -type=SRV _memcached-client._tcp.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local
  Server:         127.0.0.53
  Address:        127.0.0.53#53
  
  Non-authoritative answer:
  _memcached-client._tcp.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local      service = 0 50 11211 mimir-distributed-chunks-cache-0.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.
  _memcached-client._tcp.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local      service = 0 50 11211 mimir-distributed-chunks-cache-1.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.
  ```

### What did you think would happen?

The dnssrvnoa+ client should work with IPv6 addresses and receive a SRV record and not AAAA.

### What was your environment?

- Mimir version: Latest (post PR #11041)
- Kubernetes:  v1.33.2-eks-931bdca (IPv6-only cluster)
- Memcached: Helm deployment as statefulset with headless services

### Any additional context to share?

Tried to just manually set all addresses back to dns+ but then run into a helm validation error: 
` .memcached.addresses'  is different from the address of the memcached instance created by the chart. (actual:  dns+mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.:11211 , expected:  dnssrvnoa+mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.:11211 )`

**Comment by jensloe-nhn** [comment]
We also ran into this problem. Our "fix" was to manually edit the mimir memcached config to use addresses similar to the ones in the [loki helm chart](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L3546). For example:

```
dnssrvnoa+_memcached-client._tcp.mimir-chunks-cache.mimir.svc
```

Edit (after rereading the issue text):
Our issue is similar, but not quite the same. We do not run mimir in an IPv6-only Kubernetes cluster, and our error log is a bit different.

```json
{
  "addresses": "dnssrvnoa+mimir-index-cache.mimir.svc.cluster.local.:11211",
  "caller": "memcached_client.go:732",
  "err": "lookup SRV records \"mimir-index-cache.mimir.svc.cluster.local.\": could not resolve \"mimir-index-cache.mimir.svc.cluster.local.\": all servers responded with errors to at least one search domain. Errs ;could not resolve mimir-index-cache.mimir.svc.cluster.local.: no servers returned a viable answer. Errs ;resolution against server 192.0.2.1 for mimir-index-cache.mimir.svc.cluster.local.: exchange: read udp 192.0.2.2:59238->192.0.2.1:53: i/o timeout",
  "level": "error",
  "msg": "failed to resolve addresses for memcached",
  "name": "index-cache",
  "ts": "2025-09-03T10:03:38.262443155Z"
}

```

**Comment by 56quarters** [comment]
I'm confused about what's happening here. It looks like Mimir is making a `SRV` request for the Memcached service (expected) but instead of receiving `SRV` records in response it's receiving `AAAA`. Is that accurate?

Could you run the following commands in the Kubernetes cluster Mimir is running in and share the results:

* `dig -t SRV mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.`
* `dig -t A mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.`
* `dig -t AAAA mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.`

**Comment by snapydziuba** [comment]
Thats accurate, i played around a bit thats why i had to edit the issue for "untainted values".
But thats what Loki reports. Also.. Loki works for us with dnssrvnoa.

```
dig -t SRV mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.

; <<>> DiG 9.20.11-0ubuntu0.1-Ubuntu <<>> -t SRV mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.loca
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32512
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. IN SRV

;; ANSWER SECTION:
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN SRV 0 25 9150 mimir-distributed-metadata-cache-1.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN SRV 0 25 11211 mimir-distributed-metadata-cache-0.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN SRV 0 25 9150 mimir-distributed-metadata-cache-0.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN SRV 0 25 11211 mimir-distributed-metadata-cache-1.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.

;; Query time: 28 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Sep 17 17:05:24 CEST 2025
;; MSG SIZE  rcvd: 594
```
```
dig -t A mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.

; <<>> DiG 9.20.11-0ubuntu0.1-Ubuntu <<>> -t A mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15417
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. IN A

;; Query time: 21 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Sep 17 17:06:16 CEST 2025
;; MSG SIZE  rcvd: 98
```
```
dig -t AAAA mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.

; <<>> DiG 9.20.11-0ubuntu0.1-Ubuntu <<>> -t AAAA mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54662
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. IN AAAA

;; ANSWER SECTION:
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN AAAA 2a05:d024:c0:2004:3b60::d
mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. 4 IN AAAA 2a05:d024:c0:2005:70a6::f

;; Query time: 20 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Sep 17 17:06:46 CEST 2025
;; MSG SIZE  rcvd: 154
```

**Comment by 56quarters** [comment]
Can you clarify which version of Mimir and the helm chart you're running? Does "latest" mean 2.17.1 or one of the weekly releases? Asking because there were DNS service discovery changes made _after_ 2.17 that aren't in any official release yet.

**Comment by snapydziuba** [comment]
We are currently running the Helm Chart version: 5.8.0 and Mimir with 2.17.0

**Comment by danelson** [comment]
I have a similar issue

`msg="failed to resolve addresses for memcached" addresses=dnssrvnoa+my-mimir-chunks-cache.my-mimir.svc.cluster.local.:11211 err="lookup SRV records \"my-mimir-chunks-cache.my-mimir.svc.cluster.local.\": invalid SRV response record my-mimir-chunks-cache-0.my-mimir-chunks-cache.my-mimir.svc.cluster.local.\t30\tIN\tA\t10.5.129.13"`

**Comment by RobertClarke64** [comment]
This is an issue for us too. We use mimir as a subchart, so I was able to overwrite the helper function from our chart with the old `dns+` configs instead. It seems like it's completely broken here though, so I'm quite curious as to why there has been no fix yet.

**Comment by 56quarters** [comment]
Testing in a local cluster, I see that there are A (or presumably AAAA) records returned in the "additional" section of the response. It doesn't seem like it's possible from the code to accidentally use the "additional" section as the "answer" section but it's something to look into:

```
;; >>HEADER<< opcode: Query, status: NoError, id: 46406
;; flags: Flags{qr = 1, op = Query, aa = 1, tc = 0, rd = 1, ra = 1, rc = NoError}
;; QUESTION SECTION:
; memcached-index-queries.cortex-dev-01.svc.cluster.local.                      INET    SRV
;; ANSWER SECTION:
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-5.memcached-index-queries.cortex-dev-01.svc.cluster.local.
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-4.memcached-index-queries.cortex-dev-01.svc.cluster.local.
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-2.memcached-index-queries.cortex-dev-01.svc.cluster.local.
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-1.memcached-index-queries.cortex-dev-01.svc.cluster.local.
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-3.memcached-index-queries.cortex-dev-01.svc.cluster.local.
memcached-index-queries.cortex-dev-01.svc.cluster.local.                29      INET    SRV     10 16 0 memcached-index-queries-0.memcached-index-queries.cortex-dev-01.svc.cluster.local.
;; AUTHORITY SECTION:
;; ADDITIONAL SECTION:
memcached-index-queries-5.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
memcached-index-queries-4.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
memcached-index-queries-2.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
memcached-index-queries-1.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
memcached-index-queries-3.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
memcached-index-queries-0.memcached-index-queries.cortex-dev-01.svc.cluster.local.              29      INET    A       10.XX.XX.XX
```

**Comment by 56quarters** [comment]
> This is an issue for us too. We use mimir as a subchart, so I was able to overwrite the helper function from our chart with the old `dns+` configs instead. It seems like it's completely broken here though, so I'm quite curious as to why there has been no fix yet.

There's no fix because I can't reproduce it yet. Is there anything unique about the DNS setup in your Kubernetes cluster?

**Comment by snapydziuba** [comment]
> There's no fix because I can't reproduce it yet. Is there anything unique about the DNS setup in your Kubernetes cluster?

Not really. Its just CoreDNS in an IPv6 only EKS Cluster on our side.
I should note that Loki resolves the dnssrvnoa addresses fine.

**Comment by RobertClarke64** [comment]
We are CoreDNS on EKS too, but we're IPv4.

**Comment by snapydziuba** [comment]
We would for now also be happy with just a flag in the helm chart to restore the previous behavior as we currently have to patch the config map and i also would be able to do more tests if more information is needed.

**Comment by 56quarters** [comment]
Could the people affected by this, that haven't already, run the following commands from a pod in the same namespace as Mimir and share the results (removing anything sensitive):

* `dig -t SRV mimir-distributed-metadata-cache.$NAMESPACE.svc.cluster.local.`
* `dig -t A mimir-distributed-metadata-cache.$NAMESPACE.svc.cluster.local.`
* `dig -t AAAA mimir-distributed-metadata-cache.$NAMESPACE.svc.cluster.local.`
* `cat /etc/resolv.conf`
* `ls -l /etc/resolv.conf`
* `resolvectl status`

If you are on 2.17, you can try changing this setting which uses a slightly different bit of code for doing DNS resolution. I wouldn't expect that this fixes it but it would help rule out a logic error in Mimir. I'm using `metadata_cache` as an example, update any cache configurations you'd like to test.

```
structuredConfig:
  blocks_storage:
    bucket_store:
      metadata_cache:
        memcached:
          addresses_provider: "miekgdns2"
```

**Comment by snapydziuba** [comment]
I just tested the setting for all cache options but "miekgdns2" did not fix the problem.
But as soon as i switched to golang (which also loki uses i think) this did fix our problem.

**Comment by 56quarters** [comment]
> I just tested the setting for all cache options but "miekgdns2" did not fix the problem. But as soon as i switched to golang (which also loki uses i think) this did fix our problem.

Thank you. This is an interesting datapoint. Looking at the implementation of [the golang resolver](https://github.com/golang/go/blob/5dcaf9a01b5e91074c7750823e94e08e1829cc36/src/net/lookup.go#L739-L748), it seems like it will skip any non-SRV responses to a SRV query instead of returning an error.

@snapydziuba Would you be able to try out a custom image based on 2.17 that skips non-SRV responses?

**Comment by snapydziuba** [comment]
> Would you be able to try out a custom image based on 2.17 that skips non-SRV responses?

Yes i could deploy it in our test cluster

**Comment by 56quarters** [comment]
I've pushed a test image based on 2.17.1 that _may_ fix this issue: `grafana/mimir:56quarters-release-2.17-issue-12713-a07300f607`

It is built from #13175. Note that it only applies the fix to the `miekgdns2` resolver since this resolver becomes the default in 3.0 and it was easier to log the unexpected record. This means you'll need to test with `addresses_provider: "miekgdns2"`.

**Comment by snapydziuba** [comment]
I have set the dns back to miekgdns2 and see the following logs (this is from the store-gateway):
```
ts=2025-10-28T08:11:01.722715308Z caller=bucket_stores.go:204 level=info msg="successfully synchronized TSDB blocks for all users"
ts=2025-10-28T08:11:01.72284229Z caller=gateway.go:286 level=info msg="waiting until store-gateway is ACTIVE in the ring"
ts=2025-10-28T08:11:01.847202836Z caller=gateway.go:290 level=info msg="store-gateway is ACTIVE in the ring"
ts=2025-10-28T08:11:01.847262339Z caller=mimir.go:958 level=info msg="Application started"
ts=2025-10-28T08:11:28.816122216Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-chunks-cache-0.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.\t5\tIN\tAAAA\t[INT_IPV6_PREFIX]:5:8d6e::1"
ts=2025-10-28T08:11:30.579208316Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-metadata-cache-0.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.\t4\tIN\tAAAA\t[INT_IPV6_PREFIX]:3:73a9::c"
ts=2025-10-28T08:11:30.607746698Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-index-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-index-cache-0.mimir-distributed-index-cache.monitoring-metrics.svc.cluster.local.\t5\tIN\tAAAA\t[INT_IPV6_PREFIX]:3:3d2f::1"
ts=2025-10-28T08:11:58.811605739Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-chunks-cache-0.mimir-distributed-chunks-cache.monitoring-metrics.svc.cluster.local.\t5\tIN\tAAAA\t[INT_IPV6_PREFIX]:5:8d6e::1"
ts=2025-10-28T08:12:00.579345963Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-metadata-cache-0.mimir-distributed-metadata-cache.monitoring-metrics.svc.cluster.local.\t4\tIN\tAAAA\t[INT_IPV6_PREFIX]:3:73a9::c"
ts=2025-10-28T08:12:00.627911061Z caller=resolver.go:131 level=warn msg="unexpected non-SRV response record" target=mimir-distributed-index-cache.monitoring-metrics.svc.cluster.local. record="mimir-distributed-index-cache-0.mimir-distributed-index-cache.monitoring-metrics.svc.cluster.local.\t5\tIN\tAAAA\t[INT_IPV6_PREFIX]:3:3d2f::1"
```

For the Chunks Cache i still get connections in with this setup as well as new items being stored into memcached:

<img width="462" height="204" alt="Image" src="https://github.com/user-attachments/assets/bd052da3-7774-4c8a-89bf-3af44b0adff7" />

Any specific information you are looking for?

**Comment by 56quarters** [comment]
> For the Chunks Cache i still get connections in with this setup as well as new items being stored into memcached:

Awesome, so there are still `SRV` records being returned and caching still works.

> Any specific information you are looking for?

This is enough to fix the problem. I would be helpful to understand what's going on if you could describe the DNS setup for your cluster in a little more detail. You mentioned that you were using CoreDNS. Do the nodes each run dnsmasq or systemd-resolved? I'm trying to understand which component is returning `A` / `AAAA` records in response to `SRV` query since that is surprising behavior to me.

**Comment by 56quarters** [comment]
This fix has been included in 2.17.2 published today for both resolver backends (`miekgdns` and `miekgdns2`) and will be included in future releases: `docker pull grafana/mimir:2.17.2`. Please let me know if you run into issues with it.

**Comment by snapydziuba** [comment]
I will test it and when i find time further research the DNS behaviour. 
The current info i can provide is that we use EKS with Bottlerocket images which are running systemd-resolved.

**Comment by 56quarters** [comment]
> We are CoreDNS on EKS too, but we're IPv4.

@RobertClarke64 Do your containers happen to be running `systemd-resolved` as well?

**Comment by RobertClarke64** [comment]
> > We are CoreDNS on EKS too, but we're IPv4.
> 
> [@RobertClarke64](https://github.com/RobertClarke64) Do your containers happen to be running `systemd-resolved` as well?

Yes, we're running Amazon Linux 2023 which uses systemd-resolved
