### ISSUE TITLE
Bug: recording rule 'mimir_api_2 -  cluster_job_route:cortex_request_duration_seconds:sum_rate' has no data

### ISSUE THREAD

**Issue by LuxTheDude** [grafana/mimir#12782]
### What is the bug?

The recording rule is somehow misconfigured. It's query returns no data. This results in the latency panels in Mimir / Write dashboard showing no data, as they use the rule.

Looking at the requests, it seems setting the rate from 1m up to 2m or more, does retrieve data.

### How to reproduce it?

1. Deploy Mimir distributed Helm chart
2. Install pre-compiled mixins in Grafana.
3. Execute query for the recording rule, retrieving no data.
4. verify the recording rule query works, with higher rate interval (eg. metric does exist)

### What did you think would happen?

The recording rule would retrieve proper data for use in the dashboards.

### What was your environment?

Deployment Tool: Helm
Mimir Chart version: 5.8.0
Mimir App version: 2.17.0
Mimir mixins precompiled version: 2.17.0
Grafana version: 12.1.1

**Comment by charleskorn** [comment]
What scrape interval are you using for metamonitoring? If the scrape interval is 60s, then that would explain the behaviour you are seeing.

**Comment by krajorama** [comment]
That recording rule records native histograms , I wonder if scrape is set up for that in the Helm chart? @narqo

**Comment by LuxTheDude** [comment]
> What scrape interval are you using for metamonitoring? If the scrape interval is 60s, then that would explain the behaviour you are seeing.

That might be bang on then. I am using the default scraper interval. The ServiceMonitors included in the Helm chart does not have a scrape interval set. So it defaults to the scraper. I am using alloy, which defaults to 1m. That is the problem.

I do still believe this is an issue though, i think the ServiceMonitors should set a default scrape interval that works with all recording and alerting rules.

**Comment by narqo** [comment]
We are currently deprecating the Mimir Helm chart's meta-monitoring in favour of k8s-monitoring. See the [future release docs](https://grafana.com/docs/helm-charts/mimir-distributed/next/run-production-environment-with-helm/#monitor-the-health-of-your-grafana-mimir-cluster) for details.

But for this one it's somewhere confusing,

> [..] I am using alloy, which defaults to 1m

If you deploy your own Grafana Alloy this instance should not use the ServiceMonitor, that the **deprecated** meta-monitoring provisions. These ServiceMonitors are only used for the built-in Grafana Agent, that chart deploys when `metaMonitoring.grafanaAgent.enabled=true`.

**Update** Above I wrongly stated that the ServiceMonitors aren't deployed without grafana agent. This is only true for those ServiceMonitors, that scrap k8s-metrics via kube-state-metrics. The ServiceMonitors, that scrap Mimir-own metrics are deployed with `metaMonitoring.serviceMonitor.enabled=true`. The user can set `metaMonitoring.serviceMonitor.interval` to tune their scrap interval.

Could you share more details about your installation's meta-monitoring configuration?

**Comment by LuxTheDude** [comment]
`metaMonitoring.serviceMonitor.enabled=true` is the one i am talking about, that scrapes Mimirs own metrics.

When i realised my issue came from the scraper interval, i fixed it using the `metaMonitoring.serviceMonitor.interval`.

So my issue is resolved.

However, i proposed that the `metaMonitoring.serviceMonitor.interval` should default to a value that will work with the alerts and dashboards, instead of having no value, and falling back on the default interval of the scraper used.

**Comment by eloo-abi** [comment]
Hi there,
just across this issue and i am still a bit confused.

We are using the k8s-monitoring chart with the mimir integration but its still not working. 
I guess thats the case because also in the monitoring charts mimir integration the default scrape interval is also 60s

https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-integrations/integrations/alloy-values.yaml#L29

so is the correct workaround (or long term solution) to use a scrape interval of 30s (is this really necessary to have such fine grained data?) or to adjust the recording rules to 2m or more?

**Comment by 56quarters** [comment]
> Hi there, just across this issue and i am still a bit confused.
> 
> We are using the k8s-monitoring chart with the mimir integration but its still not working. I guess thats the case because also in the monitoring charts mimir integration the default scrape interval is also 60s
> 
> https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-integrations/integrations/alloy-values.yaml#L29
> 
> so is the correct workaround (or long term solution) to use a scrape interval of 30s (is this really necessary to have such fine grained data?) or to adjust the recording rules to 2m or more?

@eloo-abi can you clarify where you are installing the mixin from? The fix for only scraping metrics at a 60s interval is to change the `scrape_interval` configuration for the mixin to 60s so that ranges automatically pick a longer value. This requires building the rules and alerts from jsonnet yourself.

**Comment by eloo-abi** [comment]
@56quarters we have just copied the rules from
https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/rules.yaml
into our mimir release helm chart

related to the scrape interval we have adjusted the scrape interval for mimir to 30s..

after the changed rules (see the open PR) we will maybe reduce our scrape interval back to 1m
