### ISSUE TITLE
Helm: mimir-distributed is using deprecated HorizontalPodAutoscaler and PodSecurityPolicy

### ISSUE THREAD

**Issue by bugfix4u** [grafana/mimir#2201]
#### Describe the bug
Deploying the helm charts in Microk8s 1.23.6 I get the following warning about deprecated values in the templates:

W0621 18:36:32.458779  374624 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0621 18:36:32.544209  374624 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W0621 18:36:32.680600  374624 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0621 18:36:32.689605  374624 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0621 18:36:33.531445  374624 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W0621 18:36:33.611586  374624 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W0621 18:36:34.826350  374624 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0621 18:36:34.982337  374624 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0621 18:36:34.987830  374624 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0621 18:36:35.107306  374624 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0621 18:36:35.110723  374624 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0621 18:36:35.143018  374624 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

#### To Reproduce

1. helm repo add grafana https://grafana.github.io/helm-charts 
2. Run either "helm install" or "helm update" on mimir 2.1.0 

#### Expected behavior

To install or update without warning about deprecated template values

#### Environment

- Infrastructure: Ubuntu Microk8s 1.23.6
- Deployment tool: helm

**Comment by yitzchake** [comment]
We're getting the same error:

```Deleting outdated charts
Release "mimir-distributed" does not exist. Installing it now.
W0721 14:50:34.102941    2006 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.[25](https://github.com/reblaze/rbz-infra-monitoring/runs/7451845209?check_suite_focus=true#step:7:26)+
W0721 14:50:40.500950    2006 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Error: failed post-install: timed out waiting for the condition
Error: Process completed with exit code 1.
``` 

Any updates or workarounds?

**Comment by dimitarvdimitrov** [comment]
I see three issues

```
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
that should be addressing [in the code](https://github.com/grafana/mimir/blob/2e599d1b07067af4f4455c7b06c3aff74b684bb7/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L316). If the kubernetes version is later than 1.21, then it should use the policy/v1 resource. I tested locally and it chooses the correct version


For 
```
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```
and 
```
autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
```

we should actually fix them, now that 1.25 is around the corner

**Comment by dimitarvdimitrov** [comment]
I will try to get the fixes for HorizontalPodAutoscaler and PodSecurityPolicy in in the coming week. They will be released in the 3.2 (or 4.0) helm chart and the weekly release right after the fix is merged.

**Comment by dimitarvdimitrov** [comment]
I realized that our pod security policy cannot actually run because the mimir containers run as root and the policy forbids that. So the PSP that we create by default prevents installing the chart.

That may be the reason for the timeout waiting for condition that @yitzchake experienced. There is this issue for making Mimir's image run as non-root https://github.com/grafana/mimir/issues/1144 and an issue to trickle this down to the helm chart #2595

I think we will have to cross that bridge one way or another and I think the time is getting closer.


### workarounds

#### k8s >=1.25

Since 1.25 removes PSP and makes Pod Security level enforcements per namespace (not as flexible as PSP), the workaround for using Pod Security admission controller is to set the privileged pod security level as _not enforced_ on the namespace in which Mimir runs. Instead setting it to audit should allow pods in:

```
kubectl label --overwrite ns $NAMESPACE pod-security.kubernetes.io/audit=privileged
```

#### k8s <1.25

for now disable rbac for the chart. `rbac.enabled: false`. I will put in a change that will change the existing PSP to actually work with what we have, so default installs work.

**Comment by dimitarvdimitrov** [comment]
hey all, a quick update:

The PSP should be removed from >1.25 as of version 3.1.0-weekly.203, will also be part of 4.0.0 (__but not 3.1.0__).

The nginx autoscaler should be fixed in 3.1.0-weekly.203 and 4.0.0.

The last linked PR should also make the existing PSP work on k8s <1.25 and will allow running with an enforced restricted policy in k8s >1.21. That same PR will close this issue too.

**Comment by rubenvw-ngdata** [comment]
@dimitarvdimitrov I think this is still being used in the latest released version of the helm chart, and still present in the current codebase.
See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml

**Comment by dimitarvdimitrov** [comment]
it is conditional on the kubernetes version https://github.com/grafana/mimir/blob/c2bf0e4d3611dc0bfe0d83f74213f164e94b4202/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L474-L479

should not be created when installing the chart on >=1.25
